// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaBdQG_5Z9aItoosQM_UTD43vE_LJHZFc',
    appId: '1:179107539448:web:3e4a5dd86784c54bf48e0d',
    messagingSenderId: '179107539448',
    projectId: 'flutter-portfolio-blog-app',
    authDomain: 'flutter-portfolio-blog-app.firebaseapp.com',
    storageBucket: 'flutter-portfolio-blog-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYnZDVRGC7956AhBGOXD2JKKJuLUGGoKQ',
    appId: '1:179107539448:android:1a94a8e08c15d023f48e0d',
    messagingSenderId: '179107539448',
    projectId: 'flutter-portfolio-blog-app',
    storageBucket: 'flutter-portfolio-blog-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYIOTl8FJWh4nB5JvRZRF-mxxzzvYf_hk',
    appId: '1:179107539448:ios:2a4ae0a2888799c4f48e0d',
    messagingSenderId: '179107539448',
    projectId: 'flutter-portfolio-blog-app',
    storageBucket: 'flutter-portfolio-blog-app.appspot.com',
    iosBundleId: 'com.example.blogapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYIOTl8FJWh4nB5JvRZRF-mxxzzvYf_hk',
    appId: '1:179107539448:ios:4d4e5f53651476aaf48e0d',
    messagingSenderId: '179107539448',
    projectId: 'flutter-portfolio-blog-app',
    storageBucket: 'flutter-portfolio-blog-app.appspot.com',
    iosBundleId: 'com.example.blogapp.RunnerTests',
  );
}
